modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="one_peice_mod"
version="1.0.0"
displayName="One Peice Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="gbtapestry, MCreator"

[[dependencies.one_peice_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




